[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.model_checker]
extCalls = "trusted"
engine = "chc"
solvers = [ "z3" ]
timeout = 1000
targets = [
	"assert"
]
showProved = true
showUnproved = true
showUnsupported = true
showProvedSafe = true

[profile.default.model_checker.contracts]
'./src/SimplifiedContract.sol' = [ "Vulnerable" ]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
